# yaml-language-server: $schema=https://raw.githubusercontent.com/RedHatInsights/frontend-components/refs/heads/master/packages/config-utils/src/feo/spec/frontend-crd.schema.json
apiVersion: v1
kind: Template
metadata:
  name: landing-page-frontend
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: landing
    spec:
      feoConfigEnabled: true
      envName: ${ENV_NAME}
      deploymentRepo: https://github.com/RedHatInsights/landing-page-frontend
      title: Landing
      image: ${IMAGE}:${IMAGE_TAG}
      API:
        versions:
          - v1
      frontend:
        paths:
          - /apps/landing
      module:
        manifestLocation: "/apps/landing/fed-mods.json"
        modules:
        - id: "landing"
          module: "./RootApp"
          routes:
          - pathname: /
            exact: true
      widgetRegistry:
        - scope: "landing"
          module: "./ExploreCapabilities"
          config:
            icon: "RocketIcon"
            title: "Explore capabilities"
          defaults:
            w: 3
            h: 5
            maxH: 10
            minH: 1
        - scope: "chrome"
          module: "./DashboardFavorites"
          featureFlag: "widget.favoriteServices.enable"
          config:
            icon: "StarIcon"
            title: "My favorite services"
            headerLink:
              title: "View all services"
              href: "/allservices"
          defaults:
            w: 1
            h: 6
            maxH: 10
            minH: 1
        - scope: "landing"
          module: "./RecentlyVisited"
          featureFlag: "widget.recentlyVisited.enable"
          config:
            icon: "HistoryIcon"
            title: "Recently visited"
          defaults:
            w: 1
            h: 7
            maxH: 10
            minH: 1
        - scope: "landing"
          module: "./SupportCaseWidget"
          config:
            icon: "HeadsetIcon"
            title: "My support cases"
            headerLink:
              title: "Open a support case"
              href: "https://access.redhat.com/support/cases/#/case/new/get-support?caseCreate=true"
          defaults:
            w: 2
            h: 4
            maxH: 10
            minH: 1
      baseWidgetLayouts:
        - name: "landingPage"
          displayName: "LandingPage"
          templateConfig:
            sm:
              - cx: 0
                cy: 0
                i: 'rhel#rhel'
                w: 1
                h: 4
                maxH: 10
                minH: 1
              - cx: 0
                cy: 1
                i: 'openshift#openshift'
                w: 1
                h: 4
                maxH: 10
                minH: 1
              - cx: 0
                cy: 2
                i: 'ansible#ansible'
                w: 1
                h: 4
                maxH: 10
                minH: 1
              - cx: 0
                cy: 3
                i: 'recentlyVisited#recentlyVisited'
                w: 1
                h: 5
                maxH: 10
                minH: 1
              - cx: 0
                cy: 4
                i: 'favoriteServices#favoriteServices'
                w: 1
                h: 4
                maxH: 10
                minH: 1
              - cx: 0
                cy: 5
                i: 'subscriptions#subscriptions'
                w: 1
                h: 6
                maxH: 10
                minH: 1
              - cx: 0
                cy: 6
                i: 'exploreCapabilities#exploreCapabilities'
                w: 1
                h: 13
                maxH: 13
                minH: 1
              - cx: 0
                cy: 7
                i: 'openshiftAi#openshiftAi'
                w: 1
                h: 4
                maxH: 10
                minH: 1
              - cx: 0
                cy: 8
                i: 'imageBuilder#imageBuilder'
                w: 1
                h: 4
                maxH: 10
                minH: 1
              - cx: 0
                cy: 9
                i: 'acs#acs'
                w: 1
                h: 4
                maxH: 10
                minH: 1
            md:
              - cx: 0
                cy: 0
                i: 'rhel#rhel'
                w: 1
                h: 4
                maxH: 10
                minH: 1
              - cx: 0
                cy: 1
                i: 'openshift#openshift'
                w: 1
                h: 4
                maxH: 10
                minH: 1
              - cx: 0
                cy: 2
                i: 'ansible#ansible'
                w: 1
                h: 4
                maxH: 10
                minH: 1
              - cx: 1
                cy: 0
                i: 'recentlyVisited#recentlyVisited'
                w: 1
                h: 3
                maxH: 10
                minH: 1
              - cx: 1
                cy: 1
                i: 'favoriteServices#favoriteServices'
                w: 1
                h: 4
                maxH: 10
                minH: 1
              - cx: 1
                cy: 2
                i: 'subscriptions#subscriptions'
                w: 1
                h: 5
                maxH: 10
                minH: 1
              - cx: 0
                cy: 3
                i: 'exploreCapabilities#exploreCapabilities'
                w: 2
                h: 6
                maxH: 10
                minH: 1
              - cx: 0
                cy: 4
                i: 'imageBuilder#imageBuilder'
                w: 1
                h: 4
                maxH: 10
                minH: 1
              - cx: 1
                cy: 4
                i: 'openshiftAi#openshiftAi'
                w: 1
                h: 4
                maxH: 10
                minH: 1
              - cx: 1
                cy: 3
                i: 'acs#acs'
                w: 2
                h: 3
                maxH: 10
                minH: 1
            lg:
              - cx: 0
                cy: 0
                i: 'rhel#rhel'
                w: 1
                h: 4
                maxH: 10
                minH: 1
              - cx: 1
                cy: 0
                i: 'openshift#openshift'
                w: 1
                h: 4
                maxH: 10
                minH: 1
              - cx: 0
                cy: 1
                i: 'ansible#ansible'
                w: 2
                h: 4
                maxH: 10
                minH: 1
              - cx: 0
                cy: 4
                i: 'exploreCapabilities#exploreCapabilities'
                w: 2
                h: 6
                maxH: 10
                minH: 1
              - cx: 2
                cy: 0
                i: 'recentlyVisited#recentlyVisited'
                w: 1
                h: 4
                maxH: 10
                minH: 1
              - cx: 2
                cy: 2
                i: 'favoriteServices#favoriteServices'
                w: 1
                h: 4
                maxH: 10
                minH: 1
              - cx: 2
                cy: 3
                i: 'subscriptions#subscriptions'
                w: 1
                h: 6
                maxH: 10
                minH: 1
              - cx: 0
                cy: 4
                i: 'openshiftAi#openshiftAi'
                w: 1
                h: 4
                maxH: 10
                minH: 1
              - cx: 1
                cy: 4
                i: 'imageBuilder#imageBuilder'
                w: 1
                h: 4
                maxH: 10
                minH: 1
              - cx: 2
                cy: 4
                i: 'acs#acs'
                w: 1
                h: 4
                maxH: 10
                minH: 1
            xl:
              - cx: 0
                cy: 0
                i: 'rhel#rhel'
                w: 1
                h: 4
                maxH: 10
                minH: 1
              - cx: 1
                cy: 0
                i: 'openshift#openshift'
                w: 1
                h: 4
                maxH: 10
                minH: 1
              - cx: 2
                cy: 0
                i: 'ansible#ansible'
                w: 1
                h: 4
                maxH: 10
                minH: 1
              - cx: 0
                cy: 2
                i: 'exploreCapabilities#exploreCapabilities'
                w: 3
                h: 6
                maxH: 10
                minH: 1
              - cx: 3
                cy: 0
                i: 'recentlyVisited#recentlyVisited'
                w: 1
                h: 3
                maxH: 10
                minH: 1
              - cx: 3
                cy: 1
                i: 'favoriteServices#favoriteServices'
                w: 1
                h: 5
                maxH: 10
                minH: 1
              - cx: 3
                cy: 2
                i: 'subscriptions#subscriptions'
                w: 1
                h: 6
                maxH: 10
                minH: 1
              - cx: 0
                cy: 3
                i: 'openshiftAi#openshiftAi'
                w: 1
                h: 4
                maxH: 10
                minH: 1
              - cx: 1
                cy: 3
                i: 'imageBuilder#imageBuilder'
                w: 1
                h: 4
                maxH: 10
                minH: 1
              - cx: 2
                cy: 3
                i: 'acs#acs'
                w: 1
                h: 4
                maxH: 10
                minH: 1
parameters:
  - name: ENV_NAME
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE
    value: quay.io/cloudservices/landing-page-frontend
