export const TECHOLOGIES = 'TECHNOLOGIES';
export const CALCULATE_ENDPOINTS = 'CALCULATE_ENDPOINTS';
export const LOAD_CAROUSEL = 'LOAD_CAROUSEL';
export const LOAD_SECTIONS = 'LOAD_SECTIONS';
export const LOAD_DATA = 'LOAD_DATA';
export const REMOVE_ESTATE_TILE = 'REMOVE_ESTATE_TILE';
