apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/RedHatInsights/landing-page-frontend?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch == "master"
    pipelinesascode.tekton.dev/pipeline: https://github.com/RedHatInsights/konflux-pipelines/raw/main/pipelines/platform-ui/docker-build-run-all-tests.yaml
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: landing-page-frontend
    appstudio.openshift.io/component: landing-page-frontend
    pipelines.appstudio.openshift.io/type: build
  name: landing-page-frontend-on-pull-request
  namespace: rh-platform-experien-tenant
spec:
  params:
  # Build configuration
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/rh-platform-experien-tenant/landing-page-frontend/landing-page-frontend:on-pr-{{revision}}
  - name: image-expires-after
    value: 5d
  - name: dockerfile
    value: build-tools/Dockerfile

  # Required test scripts
  - name: unit-tests-script
    value: |
      #!/bin/bash
      set -ex
      npm run test

  - name: e2e-tests-script
    value: |
      #!/bin/bash
      set -ex
      npx playwright test

  - name: run-app-script
    value: |
      #!/bin/bash
      set -ex
      caddy run --config /etc/caddy/Caddyfile --adapter caddyfile

  # E2E configuration (technically have defaults but must be set correctly)
  - name: e2e-playwright-image
    value: "mcr.microsoft.com/playwright:v1.40.0-jammy"

  - name: frontend-proxy-routes-configmap
    value: "landing-page-frontend-dev-proxy-caddyfile"

  - name: e2e-credentials-secret
    value: "landing-page-frontend-credentials-secret"

  # Optional (can omit to use defaults)
  - name: e2e-app-port
    value: "8000"

  pipelineRef:
    resolver: git
    params:
      - name: url
        value: https://github.com/RedHatInsights/konflux-pipelines
      - name: revision
        value: main
      - name: pathInRepo
        value: pipelines/platform-ui/docker-build-run-all-tests.yaml

  taskRunTemplate:
    serviceAccountName: build-pipeline-landing-page-frontend

  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
